"""Add event_date to queue entries for history

Revision ID: e671ece58686
Revises: 0920d1e1c43f
Create Date: 2025-11-23 18:44:01.578188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e671ece58686'
down_revision = '0920d1e1c43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем временную таблицу, если она существует
    try:
        op.drop_table('_alembic_tmp_users')
    except:
        pass
    
    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('calendar_event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_queue_entries_calendar_event_id', 'calendar_events', ['calendar_event_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('full_name_encrypted',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.alter_column('full_name_encrypted',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('calendar_event_id')
        batch_op.drop_column('event_date')

    op.create_table('_alembic_tmp_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=False),
    sa.Column('telegram_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('full_name_encrypted', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    # ### end Alembic commands ###
